server {
    listen 80;
    server_name split.api.spl-unboxed.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name split.api.spl-unboxed.com;

    ssl_certificate     /etc/letsencrypt/live/split.api.spl-unboxed.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/split.api.spl-unboxed.com/privkey.pem;

    client_max_body_size 25m;

    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;

    location / {
        proxy_pass         http://api:8000;
        proxy_http_version 1.1;

        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;

        proxy_set_header   Connection        '';
        proxy_buffering    off;
        proxy_cache        off;

    }
}
